console.log(Date.now());
console.log(new Date().getDay());
console.log(new Date().getTime());
console.log(new Date().getMilliseconds());
console.log(new Date().getSeconds());
console.log(new Date().getMinutes());
console.log(new Date().getHours());
console.log(new Date().getDate());
console.log(new Date().getMonth());
console.log(new Date().getFullYear());